version: 2
updates:
  - package-ecosystem: "gradle" 
    directory: "/" 
    schedule:
      interval: "daily"
    groups:
      springboot:
        applies-to: version-updates
        patterns:
          - "com.google.code.gson:gson"
          - "org.redisson:redisson"
          - "com.twilio.sdk:twilio"
          - "com.googlecode.libphonenumber:libphonenumber"
          - "org.testcontainers:testcontainers"
        update-types:
          - "minor"
          - "patch"
  - package-ecosystem: "github-actions" 
    directory: "/" 
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker" 
    directory: "/" 
    schedule:
      interval: "weekly"
