apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-app
spec:
  selector:
    matchLabels:
      app: springboot
  template:
    metadata:
      labels:
        app: springboot
    spec:
      containers:
        - name: springboot-container
          image: springboot
          imagePullPolicy: Never
          ports:
            - containerPort: 8087
          volumeMounts:
            - name: keystore-volume
              mountPath: /etc/letsencrypt/live/bakacore.com
      volumes:
        - name: keystore-volume
          hostPath:
            path: /etc/letsencrypt/live/bakacore.com
            type: Directory
---
apiVersion: v1
kind: Service
metadata:
  name: springboot-service
spec:
  type: LoadBalancer
  selector:
    app: springboot
  ports:
    - port: 8087
      targetPort: 8087