server.ssl.enabled=true
server.ssl.bundle=letsencrypt
spring.ssl.bundle.pem.letsencrypt.keystore.certificate=/etc/letsencrypt/live/bakacore.com/fullchain.pem
spring.ssl.bundle.pem.letsencrypt.keystore.private-key=/etc/letsencrypt/live/bakacore.com/privkey.pem