replicaCount: 1

appName: springboot

containerName: springboot-container

image:
  repository: ghcr.io/jacksonkuo/springboot
  tag: latest
  pullPolicy: Always

service:
  type: LoadBalancer
  port: 8087
  targetPort: 8087

