apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
    spec:
      containers:
        - name: {{ .Values.containerName }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          env: 
            - name: SPRING_PROFILE
              value: {{ .Values.springProfile }}
            - name: HCAPTCHA_SECRET
              valueFrom:
                secretKeyRef:
                  name: hcaptcha-secret
                  key: HCAPTCHA_SECRET
            - name: VERIFY_SERVICE_SID
              valueFrom:
                secretKeyRef:
                  name: verify-service-sid
                  key: VERIFY_SERVICE_SID
            - name: TWILIO_ACCOUNT_SID
              valueFrom:
                secretKeyRef:
                  name: twilio-account-sid
                  key: TWILIO_ACCOUNT_SID
            - name: TWILIO_AUTH_TOKEN
              valueFrom:
                secretKeyRef:
                  name: twilio-auth-token
                  key: TWILIO_AUTH_TOKEN
          volumeMounts:
            {{- if .Values.enableVolumeMounts }}
            - name: keystore-volume
              mountPath: /etc/letsencrypt/live/bakacore.com
              readOnly: true
            {{- end }}
      {{- if .Values.enableVolumeMounts }}
      volumes:
        - name: keystore-volume
          hostPath:
            path: /etc/letsencrypt/live/bakacore.com
            type: Directory
      {{- end }}

