apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
    spec:
      containers:
        - name: {{ .Values.containerName }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          volumeMounts:
            - name: keystore-volume
              mountPath: /etc/letsencrypt/live/bakacore.com 
              readOnly: true 
        - name: redis
          image: redis:latest
          ports:
            - containerPort: 6379
      volumes:
        - name: keystore-volume
          hostPath:
            path: /etc/letsencrypt/live/bakacore.com
            type: Directory
