{{- if .Values.enableAppGin }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-gin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-gin
  template:
    metadata:
      labels:
        app: app-gin
    spec:
      containers:
        - name: app-gin
          image: "{{ .Values.ginImage.repository }}:{{ .Values.ginImage.tag }}"
          imagePullPolicy: "{{ .Values.ginImage.pullPolicy }}"
          ports:
            - containerPort: 2096
          env:
            - name: OKTA_OAUTH2_ISSUER
              valueFrom:
                secretKeyRef:
                  name: okta-creds
                  key: OKTA_OAUTH2_ISSUER
            - name: OKTA_OAUTH2_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: okta-creds
                  key: OKTA_OAUTH2_CLIENT_ID
            - name: OKTA_OAUTH2_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: okta-creds
                  key: OKTA_OAUTH2_CLIENT_SECRET
            - name: OKTA_OAUTH2_SESSION_KEY
              valueFrom:
                secretKeyRef:
                  name: okta-creds
                  key: OKTA_OAUTH2_SESSION_KEY
            - name: OKTA_REDIRECT_URI
              value: "https://bakacore.com:2096/authorization-code/callback"
          volumeMounts:
            {{- if .Values.enableVolumeMounts }}
            - name: le-live
              mountPath: /etc/letsencrypt/live
              readOnly: true
            - name: le-archive
              mountPath: /etc/letsencrypt/archive
              readOnly: true
            {{- end }}
      {{- if .Values.enableVolumeMounts }}
      volumes:
        - name: le-live
          hostPath:
            path: /etc/letsencrypt/live
            type: Directory
        - name: le-archive
          hostPath:
            path: /etc/letsencrypt/archive
            type: Directory
      {{- end }}
{{- end }}
