name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout src
      uses: actions/checkout@v4

    - name: Set up JDK 
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build with Gradle
      run: |
        chmod +x ./gradlew
        ./gradlew build

    - name: Build Helm Chart
      run: | 
        helm package ./springboot-chart

    - name: Publish to Latest Release
      run: |
        if gh release view latest; then
          echo "Release exists. Deleting old release..."
          gh release delete latest --yes
        fi

        gh release create latest springboot-chart-0.0.1.tgz \
          --title "Latest Release" \
          --notes "This is the latest helm chart" \
          --prerelease
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Log in to GHCR
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin

    - name: Build Docker image
      run: docker build -t ghcr.io/jacksonkuo/springboot:latest -f Dockerfile.prod .

    - name: Push Docker image to GHCR
      run: docker push ghcr.io/jacksonkuo/springboot:latest

    - name: SSH
      run: |
        echo 'Setup SSH...'
        install -m 600 -D /dev/null ~/.ssh/id_ed25519
        echo "$DROPLET_SSH_PRIVATE_KEY" > ~/.ssh/id_ed25519

        ssh -o StrictHostKeyChecking=no root@$DROPLET_IP "
          echo 'Install JDK...'
          apt -qq update && apt-get -qq install -y openjdk-17-jdk-headless
          echo 'Downloading the latest JAR...'

          echo 'Install Helm 3...'
          curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
          chmod 700 get_helm.sh
          ./get_helm.sh

          echo 'Check for K3s...'
          if k3s --version &> /dev/null; then
            echo "K3s is already installed."
          else
            echo 'Install K3s...'
            curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC='--disable metrics-server --disable traefik' sh -
          fi

          echo 'Download Helm chart...'
          curl -LO https://github.com/JacksonKuo/app-springboot/releases/download/latest/springboot-chart-0.0.1.tgz
          export KUBECONFIG=/etc/rancher/k3s/k3s.yaml

          echo 'Deploy Spring Boot service...'
          helm uninstall springboot
          helm install springboot springboot-chart-0.0.1.tgz"      
      env:
        DROPLET_IP: ${{ secrets.DROPLET_IP }}
        DROPLET_SSH_PRIVATE_KEY: ${{ secrets.DROPLET_SSH_PRIVATE_KEY }}
        HCAPTCHA_SECRET: ${{ secrets.HCAPTCHA_SECRET }}


    

