name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout src
      uses: actions/checkout@v4

    - name: Set up JDK 
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build with Gradle
      run: |
        chmod +x ./gradlew
        ./gradlew build

    - name: Publish to Latest Release
      run: |
        if gh release view latest; then
          echo "Release exists. Deleting old release..."
          gh release delete latest --yes
        fi

        gh release create latest build/libs/sample-0.0.1-SNAPSHOT.jar \
          --title "Latest Release" \
          --notes "This is the latest build of the application." \
          --prerelease
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Log in to GHCR
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin

    - name: Build Docker image
      run: docker build -t ghcr.io/jacksonkuo/springboot:latest .

    - name: Push Docker image to GHCR
      run: docker push ghcr.io/jacksonkuo/springboot:latest

    - name: Make GHCR image public using gh CLI
      run: |
        gh api --method PATCH "/user/packages/container/springboot/visibility" -f visibility="public"
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: SSH
      run: |
        echo 'Setup SSH...'; 
        install -m 600 -D /dev/null ~/.ssh/id_ed25519
        echo "$DROPLET_SSH_PRIVATE_KEY" > ~/.ssh/id_ed25519
        ssh -o StrictHostKeyChecking=no root@$DROPLET_IP "
        
        echo 'Install JDK...'; 
        apt -qq update && apt-get -qq install -y openjdk-17-jdk-headless;
        echo 'Downloading the latest JAR...'; 

        echo 'Check for K3s...';
        if command -v k3s &> /dev/null; then
          echo "K3s is already installed."
        else
          echo 'Install K3s...'; 
          curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="--disable metrics-server --disable traefik" sh -
        fi
        
        echo 'Downloading the latest JAR...';
        curl -L -o /root/sample-0.0.1-SNAPSHOT.jar \
        https://github.com/JacksonKuo/app-springboot/releases/download/latest/sample-0.0.1-SNAPSHOT.jar &&
        
      env:
        DROPLET_IP: ${{ secrets.DROPLET_IP }}
        DROPLET_SSH_PRIVATE_KEY: ${{ secrets.DROPLET_SSH_PRIVATE_KEY }}
        HCAPTCHA_SECRET: ${{ secrets.HCAPTCHA_SECRET }}


    

