name: Build

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout src
      uses: actions/checkout@v4

    - name: Set up JDK 23
      uses: actions/setup-java@v4
      with:
        java-version: '23'
        distribution: 'temurin'

    - name: Change wrapper permissions
      run: chmod +x ./gradlew

    - name: Build with Gradle
      run: ./gradlew build

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
      with:
        tag_name: 0.0.1
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false

    - name: Upload JAR to Release
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: build/libs/sample-0.0.1-SNAPSHOT.jar
        asset_name: sample-0.0.1-SNAPSHOT-{{ github.run_number }}.jar
        asset_content_type: application/java-archive

    - name: SSH
      run: |
        install -m 600 -D /dev/null ~/.ssh/id_ed25519
        echo "$DROPLET_SSH_PRIVATE_KEY" > ~/.ssh/id_ed25519
        ssh -o StrictHostKeyChecking=no root@$DROPLET_IP "echo 'Hello from GitHub Actions!' > ~/file.txt"
      env:
        DROPLET_IP: ${{ secrets.DROPLET_IP }}
        DROPLET_SSH_PRIVATE_KEY: ${{ secrets.DROPLET_SSH_PRIVATE_KEY }}