name: Build

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout src
      uses: actions/checkout@v4

    - name: Set up JDK 23
      uses: actions/setup-java@v4
      with:
        java-version: '23'
        distribution: 'temurin'

    - name: Change wrapper permissions
      run: chmod +x ./gradlew

    - name: Build with Gradle
      run: ./gradlew build

    - name: Publish to Latest Release
      run: |
        if gh release view latest; then
          echo "Release exists. Deleting old release..."
          gh release delete latest --yes
        fi

        gh release create latest build/libs/sample-0.0.1-SNAPSHOT.jar \
          --title "Latest Release" \
          --notes "This is the latest build of the application." \
          --prerelease
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: SSH
      run: |
        install -m 600 -D /dev/null ~/.ssh/id_ed25519
        echo "$DROPLET_SSH_PRIVATE_KEY" > ~/.ssh/id_ed25519
        ssh -o StrictHostKeyChecking=no root@$DROPLET_IP "echo 'Hello from GitHub Actions!' > ~/file.txt"
      env:
        DROPLET_IP: ${{ secrets.DROPLET_IP }}
        DROPLET_SSH_PRIVATE_KEY: ${{ secrets.DROPLET_SSH_PRIVATE_KEY }}