name: Build

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout src
      uses: actions/checkout@v4

    - name: Set up JDK 23
      uses: actions/setup-java@v4
      with:
        java-version: '23'
        distribution: 'temurin'

    - name: Change wrapper permissions
      run: chmod +x ./gradlew

    - name: Build with Gradle
      run: ./gradlew build

    - name: Publish JAR to GitHub Packages
      run: |
        curl -u "${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}" \
         -T build/libs/sample-${{ github.run_number }}-SNAPSHOT.jar \
         "https://maven.pkg.github.com/JacksonKuo/app-springboot/com/jkuo/sample/1.0.0-${{ github.run_number }}/sample-${{ github.run_number }}-SNAPSHOT.jar"