name: Build

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout src
      uses: actions/checkout@v4

    - name: Set up JDK 
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Change wrapper permissions
      run: chmod +x ./gradlew

    - name: Build with Gradle
      run: ./gradlew build

    - name: Publish to Latest Release
      run: |
        if gh release view latest; then
          echo "Release exists. Deleting old release..."
          gh release delete latest --yes
        fi

        gh release create latest build/libs/sample-0.0.1-SNAPSHOT.jar \
          --title "Latest Release" \
          --notes "This is the latest build of the application." \
          --prerelease
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: SSH
      run: |
        install -m 600 -D /dev/null ~/.ssh/id_ed25519
        echo "$DROPLET_SSH_PRIVATE_KEY" > ~/.ssh/id_ed25519
        ssh -o StrictHostKeyChecking=no root@$DROPLET_IP "
        echo 'Install JDK...'; 
        apt -qq update && apt-get -qq install -y openjdk-17-jdk-headless;
        echo 'Downloading the latest JAR...'; 
        curl -L -o /root/sample-0.0.1-SNAPSHOT.jar \
        https://github.com/JacksonKuo/app-springboot/releases/download/latest/sample-0.0.1-SNAPSHOT.jar &&
        export HCAPTCHA_SECRET="$HCAPTCHA_SECRET"
        echo 'Restarting the web application...'; 
        systemctl stop webapp || true;
        systemctl reset-failed webapp || true;
        systemd-run --unit=webapp --description='Transient Web App Service' --property=Restart=always java -jar /root/sample-0.0.1-SNAPSHOT.jar --spring.profiles.active=prod"
      env:
        DROPLET_IP: ${{ secrets.DROPLET_IP }}
        DROPLET_SSH_PRIVATE_KEY: ${{ secrets.DROPLET_SSH_PRIVATE_KEY }}
        HCAPTCHA_SECRET: ${{ secrets.HCAPTCHA_SECRET }}


    

